server:
  port: 8189
  servlet:
    context-path: /admin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbtest
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
springdoc:
  swagger-ui:
    path: /swag

