server:
  port: 8189
  servlet:
    context-path: /admin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbtest
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

